// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
)

type Lunch struct {
	ID           int64
	Date         string
	UserID       string
	Verb         string
	Count        int64
	Participants string
	CreatedAt    sql.NullTime
}

type Vacation struct {
	ID        int64
	UserID    string
	DateFrom  string
	DateTo    string
	CreatedAt sql.NullTime
}
